### PR TITLE
Support Puppet v4.3

### PR DESCRIPTION
**Pull request by Phil-Friderici**

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
This should make the Puppet v4.3 support complete

**Comment by Phil-Friderici** [comment]
@anders-larsson @jwennerberg:
Sorry, I ment this PR, not the other one.

Should we make a new release out of that.
Or should we wait for a functional change ?

**Comment by anders-larsson** [comment]
I've code ready to add hiera_merge support for {user,group}_override_entries. I still haven't written spec tests though and I'm off tomorrow. So if you're willing to wait with the new version until Monday it could be included in that version.

**Comment by Phil-Friderici** [comment]
@anders-larsson: great that let's wait with the new release until you have added that functionality.
PS: let me know if you need help adding hiera to the spec tests.

**Comment by Phil-Friderici** [comment]
recreated this PR against new development branch here https://github.com/Ericsson/puppet-module-vas/pull/76

**Pull request closed without merging**
