### PR TITLE
Add default_cc_name to vas.conf

### PR DESCRIPTION
**Pull request by erobhal**
We need the possibility to change the location where QAS is storing the kerberos ticket cache.

https://support.oneidentity.com/authentication-services/kb/230864

BR/ Robert

### CODE REVIEW

**Comment by erobhal** [comment]
Ping @Phil-Friderici

**Comment by Phil-Friderici** [comment]
Thanks @erobhal for your work and sorry for the delayed review.
Have added a test and merged it in https://github.com/Ericsson/puppet-module-vas/pull/130.
Will work on the other open PRs before I create a new release. Hope that's ok.

**Comment by erobhal** [comment]
NP. Thank you Phil.

**Comment by Phil-Friderici** [comment]
Released in v0.24.0 :)

**Pull request merged**
