### PR TITLE
Add ability to just unjoin domain

### PR DESCRIPTION
**Pull request by propyless**

### CODE REVIEW

**Comment by propyless** [comment]
lemme just do some tests on live staging servers

**Comment by propyless** [comment]
```
puppet agent -t --environment test_vas
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for themostawesomenode.awesome.com
Info: Applying configuration version 'this_cataogue_was_generated_by_the_best_server'
Notice: /Stage[main]/Vas/Exec[vas_unjoin]/returns: executed successfully
Notice: Finished catalog run in 14.18 seconds
[root@themostawesomenode ~]# /opt/quest/bin/vastool status
Host:   <themostawesomenode.awesome.com, Linux x86_64>
Date:   <Fri Apr 29 10:38:09 CEST 2016>
QAS:    <4.1.0>
Domain: <N/A>
CRITICAL: 106 /etc/opt/quest/vas/vas.conf missing default_realm setting, is QAS joined?
Result: <Critical test(s) failed> (0 seconds)(v0.7.6)
```

**Comment by propyless** [comment]
@Phil-Friderici ping!

**Comment by Phil-Friderici** [comment]
@propyless looks like the code has much more changes than the tests. How come ?

**Comment by Phil-Friderici** [comment]
@propyless never mind! The diff doesn't show the changed indenting very well.

**Comment by propyless** [comment]
:)

Mvh
Takeshi

**Comment by propyless** [comment]
I have identified some issues with the PR which I will resolve...

**Comment by Phil-Friderici** [comment]
@propyless you'll need to add this to your Puppet code:
<pre>
# lint:ignore:only_variable_string
</pre>

like here: https://github.com/Phil-Friderici/puppet-module-clearcase/blob/1f6c6a3503eba12fbf518b148da3f6f28be367ca/manifests/ccvobmnt.pp#L188

**Comment by propyless** [comment]
You are linking to a private repository to which I do not have access ;)

**Comment by Phil-Friderici** [comment]
oh! sorry, but I see you got the idea :)

**Comment by propyless** [comment]
I also added a bonus commit that fixes the logic in the if statement for vas migration part.

**Comment by Phil-Friderici** [comment]
got positive feedback from our VAS specialist :)

**Comment by Phil-Friderici** [comment]
@propyless Thanks a lot! Released in v0.18.0
Enjoy your vacation days  :sunny: have phun and a good start afterwards :four_leaf_clover:

**Pull request merged**
