### PR TITLE
Three new parameters in libdefaults

### PR DESCRIPTION
**Pull request by skalmelid**
Add support for three new parameters in the libdefaults section:
vas_conf_libdefaults_tgs_default_enctypes
vas_conf_libdefaults_tkt_default_enctypes
vas_conf_libdefaults_default_etypes

The default values for the parameters are unchanged,
all of them have the default value 'arcfour-hmac-md5'.

### CODE REVIEW

**Comment by skalmelid** [comment]
A new commit to remove **default_etypes_des** from the [libdefaults] part of the vas.conf file on request from @tomhur, still in issue https://github.com/Ericsson/puppet-module-vas/issues/126.

**Comment by Phil-Friderici** [comment]
Thank you @skalmelid for your work. I will work on the last open PR before I release a new version of this module.

**Comment by skalmelid** [comment]
Thanks for you help @Phil-Friderici, 
that sounds fine to me!

**Comment by Phil-Friderici** [comment]
Released in v0.24.0 :)

**Pull request merged**
