### PR TITLE
PDK 3.0.0 and metadata updated for Puppet 8

### PR DESCRIPTION
**Pull request by anders-larsson**

### CODE REVIEW

**Comment by marek130** [comment]
Good job! There is just a typo in the commit message " for Puppet **9**" (should be Puppet 8).

**Comment by anders-larsson** [comment]
Uh. Good find :p

**Comment by anders-larsson** [comment]
Currently converting templates to epp to see if it helps with the  REFERENCE.md issue.

**Comment by anders-larsson** [comment]
Well, now templates are converted to epp (should probably be a separate pull request). It did not help with the issue at hand.

**Comment by anders-larsson** [comment]
Closing this issue in favour of #152, #154, #155, and #156.

**Pull request closed without merging**
