### PR TITLE
Convert function api_fetch to new format, add parameter for TLS verify mode

### PR DESCRIPTION
**Pull request by anders-larsson**
Previously OpenSSL::SSL::VERIFY_NONE was enabled by default. It really shouldn't to be honest. Added a parameter with default `true` (previous default would've been false if it existed). Probably requires a major release.

It's either this or remove the "functionality" altogether (would regardless be a new major release I guess)? You really shouldn't do unverified TLS connections.

### CODE REVIEW

**Review by Phil-Friderici — APPROVED** [review]
Didn't checked the API code in detail but it look plausible to me.

**Comment by anders-larsson** [comment]
To avoid breaking compatibility I'll change it to false by default instead of true. This will avoid us having to release a new major release until we have more breaking changes to do.

**Comment by anders-larsson** [comment]
Haven't been able to figure out if it's possible to spec test options for OpenSSL yet though. Would probably be a nice additional to actually test whether it's enabled or not.

**Comment by anders-larsson** [comment]
Tested this functionality with a real Puppet run. Works correctly to switch on TLS verification.

**Pull request merged**
