### PR TITLE
convert module to Puppet 7 (WIP)

### PR DESCRIPTION
**Pull request by Phil-Friderici**

### CODE REVIEW

**Comment by anders-larsson** [comment]
IMHO: We should be able to remove all _hiera_merge parameters. This can be handled directly in Hiera[1] instead of in the Puppet module in newer versions of Hiera.

[1]: https://puppet.com/docs/puppet/7/hiera_merging.html#overriding-merge-behavior

**Comment by Phil-Friderici** [comment]
> IMHO: We should be able to remove all _hiera_merge parameters. This can be handled directly in Hiera[1](https://puppet.com/docs/puppet/7/hiera_merging.html#overriding-merge-behavior) instead of in the Puppet module in newer versions of Hiera.

Thanks I did miss that. Let me remove them with a later commit.

**Comment by Phil-Friderici** [comment]
I have fixed most of the commit messages to follow the guide in https://cbea.ms/git-commit/.
My proposal is to all "Use new variable validation" messages into one before merging once we are satisfied with the result.

**Comment by anders-larsson** [comment]
We might want to re-add a README with at least some information :)

**Comment by Phil-Friderici** [comment]
> We might want to re-add a README with at least some information :)

Re-added README.md into https://github.com/Ericsson/puppet-module-vas/pull/140 that was auto-generated via
`puppet strings generate manifests/init.pp --format markdown --out README.md`

**Pull request merged**
